#!/usr/bin/env bash
set -euo pipefail
# Clones every sibling repo (if not already present) and wires the
# env vars agent-swarm-topology's swarm.config.json expects.
# Run this FROM platform-agent-stack/, once, before anything else.
#
# Writes stack.env — source that from your shell (or .envrc) afterwards.
# This script cannot export into your parent shell; nothing that runs as
# a subprocess can.

ORG="${GH_ORG:?set to your GitHub org, e.g. polarpoint-io}"
BASE_DIR="${BASE_DIR:-..}"
ITSM_PROVIDER="${ITSM_PROVIDER:?set to a name under itsm-providers/, e.g. freshservice}"

# --- Ruflo version -----------------------------------------------------
# Pinned deliberately. Do NOT change back to @latest: versions before
# 3.16.3 ship a docker-compose default that exposes the MCP bridge's
# POST /mcp endpoints with no auth (CVE-2026-59726 "RufRoot", CVSS 10.0
# — unauthenticated RCE, key theft, agent-memory poisoning).
# Advisory: GHSA-c4hm-4h84-2cf3
RUFLO_MIN_VERSION="3.16.3"
RUFLO_VERSION="${RUFLO_VERSION:-3.30.2}"

# Refuse to run below the patched floor, however RUFLO_VERSION was set.
if [ "$(printf '%s\n%s\n' "$RUFLO_MIN_VERSION" "$RUFLO_VERSION" \
        | sort -V | head -n1)" != "$RUFLO_MIN_VERSION" ]; then
  echo "ERROR: RUFLO_VERSION=$RUFLO_VERSION is below the patched floor $RUFLO_MIN_VERSION" >&2
  echo "       (CVE-2026-59726 — unauthenticated RCE in the MCP bridge). Refusing." >&2
  exit 1
fi

REPOS=(ruflo-bridge agent-swarm-topology mongostate-crossplane
       llm-inference-providers itsm-providers confluence-toolset
       agent-risk-policy)

for r in "${REPOS[@]}"; do
  if [ ! -d "$BASE_DIR/$r" ]; then
    gh repo clone "$ORG/$r" "$BASE_DIR/$r"
  fi
done

ITSM_PROVIDERS_REPO="$(cd "$BASE_DIR/itsm-providers" && pwd)"
RISK_POLICY_REPO="$(cd "$BASE_DIR/agent-risk-policy" && pwd)"
CONFLUENCE_TOOLSET_REPO="$(cd "$BASE_DIR/confluence-toolset" && pwd)"
SWARM_TOPOLOGY_REPO="$(cd "$BASE_DIR/agent-swarm-topology" && pwd)"
export ITSM_PROVIDERS_REPO RISK_POLICY_REPO CONFLUENCE_TOOLSET_REPO SWARM_TOPOLOGY_REPO

# --- Locate the provider file -----------------------------------------
# TODO(unresolved): this script and agent-swarm-topology disagree about
# itsm-providers' layout. swarm.config.json points actionMapping at
#   $ITSM_PROVIDERS_REPO/action-mappings/${ITSM_PROVIDER}.yaml
# i.e. a subdirectory, while this script historically expected the
# .mcp.json at the repo root. Until itsm-providers is checked in and one
# convention wins, try both and say which candidates were tried.
PROVIDER_FILE=""
for candidate in \
  "$ITSM_PROVIDERS_REPO/providers/${ITSM_PROVIDER}.mcp.json" \
  "$ITSM_PROVIDERS_REPO/${ITSM_PROVIDER}.mcp.json"
do
  if [ -f "$candidate" ]; then PROVIDER_FILE="$candidate"; break; fi
done

if [ -z "$PROVIDER_FILE" ]; then
  echo "ERROR: no provider file for ITSM_PROVIDER=$ITSM_PROVIDER. Tried:" >&2
  echo "  $ITSM_PROVIDERS_REPO/providers/${ITSM_PROVIDER}.mcp.json" >&2
  echo "  $ITSM_PROVIDERS_REPO/${ITSM_PROVIDER}.mcp.json" >&2
  exit 1
fi
echo "Using provider file: $PROVIDER_FILE"

# The matching action-mapping must exist too — swarm.config.json will
# resolve this path at run time, and a missing mapping means ungated
# verbs reaching the ITSM backend. Fail here instead.
ACTION_MAPPING="$ITSM_PROVIDERS_REPO/action-mappings/${ITSM_PROVIDER}.yaml"
[ -f "$ACTION_MAPPING" ] || {
  echo "ERROR: no action mapping at $ACTION_MAPPING" >&2
  echo "       agent-risk-policy gates generic verbs; without this mapping they" >&2
  echo "       cannot be resolved to real tool names." >&2
  exit 1
}

# --- Merge the provider into ruflo-bridge's .mcp.json ------------------
BRIDGE_MCP="$BASE_DIR/ruflo-bridge/.mcp.json"
[ -f "$BRIDGE_MCP" ] || { echo "ERROR: $BRIDGE_MCP not found" >&2; exit 1; }

BACKUP="$BRIDGE_MCP.bak.$(date -u +%Y%m%dT%H%M%SZ)"
cp "$BRIDGE_MCP" "$BACKUP"
echo "Backed up existing .mcp.json to $BACKUP"

TMP_MCP="$(mktemp)"
trap 'rm -f "$TMP_MCP"' EXIT
jq -s '.[0].mcpServers.itsm = .[1].itsm | .[0]' \
  "$BRIDGE_MCP" "$PROVIDER_FILE" > "$TMP_MCP"
jq -e . "$TMP_MCP" >/dev/null || { echo "ERROR: merge produced invalid JSON" >&2; exit 1; }
cp "$TMP_MCP" "$BRIDGE_MCP"

# --- Bring up the swarm ------------------------------------------------
SWARM_CONFIG="$SWARM_TOPOLOGY_REPO/swarm.config.json"
MAX_AGENTS="$(jq -r '.maxAgents' "$SWARM_CONFIG")"
TOPOLOGY="$(jq -r '.topology' "$SWARM_CONFIG")"

claude mcp add ruflo -- npx "ruflo@${RUFLO_VERSION}" mcp start
npx "ruflo@${RUFLO_VERSION}" swarm init \
  --topology "$TOPOLOGY" --max-agents "$MAX_AGENTS"

# --- Persist the env vars ---------------------------------------------
ENV_FILE="$(pwd)/stack.env"
cat > "$ENV_FILE" <<EOF
# Generated by platform-agent-stack/setup.sh — safe to regenerate.
export ITSM_PROVIDERS_REPO="$ITSM_PROVIDERS_REPO"
export RISK_POLICY_REPO="$RISK_POLICY_REPO"
export CONFLUENCE_TOOLSET_REPO="$CONFLUENCE_TOOLSET_REPO"
export SWARM_TOPOLOGY_REPO="$SWARM_TOPOLOGY_REPO"
export ITSM_PROVIDER="$ITSM_PROVIDER"
export RUFLO_VERSION="$RUFLO_VERSION"
EOF

echo
echo "Stack wired (ruflo ${RUFLO_VERSION}, topology ${TOPOLOGY}, max-agents ${MAX_AGENTS})."
echo "Repo paths written to $ENV_FILE — this script cannot set them in your"
echo "shell, so add one of the following:"
echo "    source $ENV_FILE          # ad hoc"
echo "    echo 'source $ENV_FILE' >> ~/.zshrc"
echo "    echo 'source ./stack.env' >> .envrc && direnv allow"
echo
echo "Before exposing the bridge: confirm ruflo-bridge's MCP endpoint is not"
echo "reachable beyond its NetworkPolicy peers. The RufRoot fix closed the"
echo "default docker-compose exposure; it does not authenticate an endpoint"
echo "you deliberately publish."
