{{- if .Values.mongoState.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "platform-agent-stack.fullname" . }}-mongo
  labels: {{- include "platform-agent-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: controller-cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ include "platform-agent-stack.fullname" . }}-mongo
    creationPolicy: Owner
  data:
    {{- range list "MONGO_URI" "MONGO_HOST" "MONGO_USERNAME" "MONGO_PASSWORD" }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.mongoState.remoteSecretName }}
        property: {{ . }}
    {{- end }}
{{- end }}
